@extends('layouts.admin')

@php
    $isEdit = isset($article);
@endphp

@section('title', ($isEdit ? 'Edit Article' : 'Publish Article') . ' - Admin Control Center')

@section('admin_content')
<div>
    <div class="mb-8 flex items-center justify-between">
        <div>
            <a href="{{ route('admin.news') }}" class="text-xs text-brand-cyan hover:underline">← Back to publications</a>
            <h1 class="text-2xl font-bold text-brand-white mt-2">
                {{ $isEdit ? 'Modify News Publication' : 'Compose News Publication' }}
            </h1>
            <p class="text-sm text-brand-gray mt-1">Configure markdown contents, custom author bio metrics, and search engine optimization parameters.</p>
        </div>
    </div>

    <form action="{{ $isEdit ? route('admin.news.update', $article->id) : route('admin.news.store') }}" method="POST" class="space-y-8">
        @csrf
        
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
            
            <!-- Left Pane: Base content settings -->
            <div class="lg:col-span-2 space-y-6">
                
                <div class="glass-card rounded-2xl p-6 border border-brand-teal/15 space-y-5">
                    <h3 class="text-xs font-extrabold uppercase tracking-wider text-brand-cyan border-b border-brand-teal/10 pb-3">Publication Body</h3>
                    
                    <!-- Title -->
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Title</label>
                        <input type="text" 
                               name="title" 
                               value="{{ old('title', $article->title ?? '') }}" 
                               required 
                               placeholder="e.g. Advancing Decentralized CBT Network Architecture..."
                               class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                    </div>

                    <!-- Content -->
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2 font-mono">Article Markdown Content</label>
                        <textarea name="content" 
                                  rows="12" 
                                  required 
                                  placeholder="Write content here. HTML elements and line breaks are preserved."
                                  class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 p-4 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none font-mono leading-relaxed transition-all">{{ old('content', $article->content ?? '') }}</textarea>
                    </div>

                    <!-- Excerpt -->
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Short Excerpt (Summary)</label>
                        <textarea name="excerpt" 
                                  rows="3" 
                                  placeholder="Short 1-2 sentence description. Autogenerated if empty."
                                  class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 p-4 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">{{ old('excerpt', $article->excerpt ?? '') }}</textarea>
                    </div>
                </div>

                <!-- Custom Author Card -->
                <div class="glass-card rounded-2xl p-6 border border-brand-teal/15 space-y-5">
                    <h3 class="text-xs font-extrabold uppercase tracking-wider text-brand-cyan border-b border-brand-teal/10 pb-3">Custom Author Parameters</h3>
                    
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-xs font-bold text-brand-white uppercase mb-2">Author Name</label>
                            <input type="text" 
                                   name="author_name" 
                                   value="{{ old('author_name', $article->author_name ?? 'Diwebs Editorial') }}" 
                                   class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                        </div>
                        <div>
                            <label class="block text-xs font-bold text-brand-white uppercase mb-2">Author Avatar URL</label>
                            <input type="url" 
                                   name="author_avatar" 
                                   value="{{ old('author_avatar', $article->author_avatar ?? '') }}" 
                                   placeholder="https://..."
                                   class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                        </div>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Author Biography Bio</label>
                        <textarea name="author_bio" 
                                  rows="3" 
                                  placeholder="Custom biography notes..."
                                  class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 p-4 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">{{ old('author_bio', $article->author_bio ?? '') }}</textarea>
                    </div>
                </div>

            </div>

            <!-- Right Pane: Meta and Category configurations -->
            <div class="space-y-6">
                
                <div class="glass-card rounded-2xl p-6 border border-brand-teal/15 space-y-5">
                    <h3 class="text-xs font-extrabold uppercase tracking-wider text-brand-cyan border-b border-brand-teal/10 pb-3">Metadata</h3>
                    
                    <!-- Category -->
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Category</label>
                        <select name="category" required class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                            @foreach($categories as $cat)
                                <option value="{{ $cat }}" {{ old('category', $article->category ?? '') === $cat ? 'selected' : '' }}>{{ $cat }}</option>
                            @endforeach
                        </select>
                    </div>

                    <!-- Status -->
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Status</label>
                        <select name="status" required class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                            <option value="draft" {{ old('status', $article->status ?? '') === 'draft' ? 'selected' : '' }}>Draft</option>
                            <option value="published" {{ old('status', $article->status ?? '') === 'published' ? 'selected' : '' }}>Published</option>
                            <option value="archived" {{ old('status', $article->status ?? '') === 'archived' ? 'selected' : '' }}>Archived</option>
                        </select>
                    </div>

                    <!-- Featured Image -->
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Featured Image URL</label>
                        <input type="url" 
                               name="featured_image" 
                               value="{{ old('featured_image', $article->featured_image ?? '') }}" 
                               placeholder="https://..."
                               class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                    </div>
                </div>

                <!-- SEO Metadata Card -->
                <div class="glass-card rounded-2xl p-6 border border-brand-teal/15 space-y-5">
                    <h3 class="text-xs font-extrabold uppercase tracking-wider text-brand-cyan border-b border-brand-teal/10 pb-3">Search Engine Optimization</h3>
                    
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Meta Title</label>
                        <input type="text" 
                               name="meta_title" 
                               value="{{ old('meta_title', $article->meta_title ?? '') }}" 
                               class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Meta Description</label>
                        <textarea name="meta_description" 
                                  rows="3" 
                                  class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 p-4 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">{{ old('meta_description', $article->meta_description ?? '') }}</textarea>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-brand-white uppercase mb-2">Meta Keywords</label>
                        <input type="text" 
                               name="meta_keywords" 
                               value="{{ old('meta_keywords', $article->meta_keywords ?? '') }}" 
                               placeholder="cbt, cyber, security, lms"
                               class="w-full rounded-lg bg-brand-dark-secondary border border-brand-teal/15 px-4 py-2.5 text-xs text-brand-white focus:border-brand-cyan/60 focus:outline-none transition-all">
                    </div>
                </div>

                <div class="flex gap-4">
                    <a href="{{ route('admin.news') }}" class="flex-1 rounded-lg border border-brand-teal/20 px-4 py-2.5 text-center text-xs font-bold text-brand-white hover:bg-brand-teal/10 transition-all">
                        Cancel
                    </a>
                    <button type="submit" class="flex-1 rounded-lg bg-gradient-to-r from-brand-teal to-brand-cyan px-4 py-2.5 text-center text-xs font-bold text-brand-dark-secondary shadow hover:opacity-90 transition-all cursor-pointer">
                        Save Article
                    </button>
                </div>

            </div>

        </div>

    </form>
</div>
@endsection
